---------------------------------------
Begin Slurm Prolog: Apr-25-2025 20:32:00
Job ID:    2536742
User ID:   dnguyen448
Account:   coc
Job name:  evaluateGene
Partition: ice-gpu
QOS:       coe-ice
---------------------------------------
Launching Python Evaluation
atl1-1-02-011-32-0.pace.gatech.edu

CondaError: Run 'conda init' before 'conda deactivate'

PARAMETER ...
Namespace(use_cpu=False, gpu='0', batch_size=216, model='pointnet2_cls_ssg_xXxAbtLceUU6MFG0E8deFRzT15P', num_category=40, epoch=2, learning_rate=0.001, num_point=1024, optimizer='Adam', log_dir=None, decay_rate=0.0001, use_normals=False, process_data=False, use_uniform_sample=False, data='/storage/ice-shared/vip-vvk/data/llm_ge_data/modelnet40_normal_resampled', end_lr=0.001, seed=21, val_r=0.2, amp=True)
Load dataset ...
The size of train data is 9843
The size of test data is 2468
3.0
3.0
3.0
No existing model, starting training from scratch...
Epoch 1 (1/2):
  0%|          | 0/45 [00:00<?, ?it/s]  0%|          | 0/45 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/storage/ice1/3/9/dnguyen448/LLM-Guided-Evolution-Generic/./sota/Pointnet_Pointnet2_pytorch/train_classification.py", line 283, in <module>
    main(args)
  File "/storage/ice1/3/9/dnguyen448/LLM-Guided-Evolution-Generic/./sota/Pointnet_Pointnet2_pytorch/train_classification.py", line 224, in main
    pred, trans_feat = classifier(points)
  File "/home/hice1/dnguyen448/.conda/envs/llm_guided_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hice1/dnguyen448/.conda/envs/llm_guided_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hice1/dnguyen448/scratch/LLM-Guided-Evolution-Generic/sota/Pointnet_Pointnet2_pytorch/models/llmge_models/pointnet2_cls_ssg_xXxAbtLceUU6MFG0E8deFRzT15P.py", line 31, in forward
    l2_xyz, l2_points = self.sa2(l1_xyz, l1_points)
  File "/home/hice1/dnguyen448/.conda/envs/llm_guided_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hice1/dnguyen448/.conda/envs/llm_guided_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/storage/ice1/3/9/dnguyen448/LLM-Guided-Evolution-Generic/sota/Pointnet_Pointnet2_pytorch/models/pointnet2_utils.py", line 198, in forward
    new_points =  F.relu(bn(conv(new_points)))
  File "/home/hice1/dnguyen448/.conda/envs/llm_guided_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hice1/dnguyen448/.conda/envs/llm_guided_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hice1/dnguyen448/.conda/envs/llm_guided_env/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 193, in forward
    return F.batch_norm(
  File "/home/hice1/dnguyen448/.conda/envs/llm_guided_env/lib/python3.9/site-packages/torch/nn/functional.py", line 2822, in batch_norm
    return torch.batch_norm(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.69 GiB. GPU 0 has a total capacity of 15.77 GiB of which 1.01 GiB is free. Including non-PyTorch memory, this process has 14.76 GiB memory in use. Of the allocated memory 13.01 GiB is allocated by PyTorch, and 1.38 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
---------------------------------------
Begin Slurm Epilog: Apr-25-2025 20:32:16
Job ID:        2536742
User ID:       dnguyen448
Account:       coc
Job name:      evaluateGene
Resources:     cpu=12,gres/gpu:v100=1,mem=16G,node=1
Rsrc Used:     cput=00:03:24,vmem=0,walltime=00:00:17,mem=2068640K,energy_used=0
Partition:     ice-gpu
QOS:           coe-ice
Nodes:         atl1-1-02-011-32-0
---------------------------------------
